models/author.py
class Author:
    def __init__(self, name, id=None):
        self.name= name
        self.id=id

models/book.py
class Book:
    def __init__(self, title, genre, author, id=None):
        self.title = title
        self.genre = genre
        self.author = author
        self.id = id

app.py
from flask import Flask, render_template

from controllers.book_controller import book_blueprint

app = Flask(__name__)

app.register_blueprint(book_blueprint)

@app.route('/')
def home():
    return render_template('index.html')

if __name__ == '__main__':
    app.run(debug=True)

controllers/book_controller.py
from flask import Flask, render_template
from flask import Blueprint
from models.book import Book
import repositories.book_repository as book_repository

book_blueprint = Blueprint("books", __name__)

@book_blueprint.route("/books")
def books():
    books = book_repository.select_all()
    return render_template("books/index.html", all_books= books)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Book Library</title>
</head>
<body>
    <header>
        <nav>
            <ul>
                <li> <a href="{{url_for('home') }}">Home</a></li>
                <li> <a href="{{url_for('books.books')}}">Books</a></li>
                <li> <a href="">New Books</a></li>
            </ul>
        </nav>
    </header>
    <div>
        {% block content %}
        {% endblock content %}
    </div>

    {% block home %}
    {% endblock home %}
</body>
</html>

templates/books/index.html
{% extends 'base.html' %}

{% block content %}

{% for book in all_books %}
    {{book.title}} <br>
    <p>Genre:{{book.genre}}</p>
    <p>Author:</p>
    <hr>
{% endfor %}
    
{% endblock content %}

templates/index.html
{% extends 'base.html' %}

{% block home %}
<section id="home-image">
<h1>Welcome to your library!</h1>
</section>
    
{% endblock home %}